//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Extensions.FluentIconFinder {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluentIconFinder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentIconFinder() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Extensions.FluentIconFinder.FluentIconFinder", typeof(FluentIconFinder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Fluent System Icon Finder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name for Android に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AndroidNameTitle {
            get {
                return ResourceManager.GetString("AndroidNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CodeTitle {
            get {
                return ResourceManager.GetString("CodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColmunNameIcon {
            get {
                return ResourceManager.GetString("ColmunNameIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnNameCode {
            get {
                return ResourceManager.GetString("ColumnNameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnNameName {
            get {
                return ResourceManager.GetString("ColumnNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for Fluent System Icons to obtain character codes and icon name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find icons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FindIconsTitle {
            get {
                return ResourceManager.GetString("FindIconsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of found icons: Double-click to select the row. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IconListTitle {
            get {
                return ResourceManager.GetString("IconListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Name for iOS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IosNameTitle {
            get {
                return ResourceManager.GetString("IosNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fluent Icon Finder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fluent Icon Finder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
